apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: DataSource
metadata:
  annotations:
    crossplane.io/external-create-pending: "2024-02-25T01:58:02Z"
    crossplane.io/external-create-succeeded: "2024-02-25T01:58:03Z"
    crossplane.io/external-name: "8:4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"oss.grafana.crossplane.io/v1alpha1","kind":"DataSource","metadata":{"annotations":{},"name":"datasource"},"spec":{"forProvider":{"basicAuthEnabled":true,"basicAuthUsername":"username","name":"datasource","organizationRef":{"name":"example-organization"},"type":"prometheus","url":"http://prometheus:9092"},"providerConfigRef":{"name":"default"}}}
    upjet.crossplane.io/provider-meta: '{"schema_version":"1"}'
  creationTimestamp: "2024-02-25T01:58:01Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generation: 3
  name: datasource
  resourceVersion: "962"
  uid: 781f4aec-d251-4f5c-a79d-c7f781b31cdc
spec:
  deletionPolicy: Delete
  forProvider:
    accessMode: proxy
    basicAuthEnabled: true
    basicAuthUsername: username
    isDefault: true
    jsonDataEncoded: '{}'
    name: datasource
    orgId: "8"
    organizationRef:
      name: example-organization
    type: prometheus
    uid: e7ecb956-e64a-4c30-b1a9-eafa162be5e6
    url: http://prometheus:9092
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
status:
  atProvider:
    accessMode: proxy
    basicAuthEnabled: true
    basicAuthUsername: username
    databaseName: ""
    id: "8:4"
    isDefault: true
    jsonDataEncoded: '{}'
    name: datasource
    orgId: "8"
    type: prometheus
    uid: e7ecb956-e64a-4c30-b1a9-eafa162be5e6
    url: http://prometheus:9092
    username: ""
  conditions:
  - lastTransitionTime: "2024-02-25T01:58:03Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2024-02-25T01:58:03Z"
    reason: Available
    status: "True"
    type: Ready
