apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Folder
metadata:
  annotations:
    crossplane.io/external-create-pending: "2024-02-25T01:58:02Z"
    crossplane.io/external-create-succeeded: "2024-02-25T01:58:03Z"
    crossplane.io/external-name: "8:7"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"oss.grafana.crossplane.io/v1alpha1","kind":"Folder","metadata":{"annotations":{},"name":"folder"},"spec":{"forProvider":{"organizationRef":{"name":"example-organization"},"title":"folder"},"providerConfigRef":{"name":"default"}}}
    upjet.crossplane.io/provider-meta: "null"
  creationTimestamp: "2024-02-25T01:58:01Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generation: 3
  name: folder
  resourceVersion: "961"
  uid: dd606791-3957-408d-a556-f4b8fe8e1d4c
spec:
  deletionPolicy: Delete
  forProvider:
    orgId: "8"
    organizationRef:
      name: example-organization
    title: folder
    uid: fc91eb77-27b6-442f-9de4-0f4760cec2ab
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
status:
  atProvider:
    id: "8:7"
    orgId: "8"
    parentFolderUid: ""
    preventDestroyIfNotEmpty: false
    title: folder
    uid: fc91eb77-27b6-442f-9de4-0f4760cec2ab
    url: http://grafana:3000/dashboards/f/fc91eb77-27b6-442f-9de4-0f4760cec2ab/folder
  conditions:
  - lastTransitionTime: "2024-02-25T01:58:03Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2024-02-25T01:58:03Z"
    reason: Available
    status: "True"
    type: Ready
