apiVersion: meta.pkg.crossplane.io/v1beta1
kind: Provider
metadata:
  name: provider-grafana
  annotations:
    meta.crossplane.io/maintainer: Crossplane Maintainers <info@crossplane.io>
    meta.crossplane.io/source: github.com/argannor/provider-grafana
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      A grafana that can be used to create Crossplane providers.
